### ISSUE TITLE
RPi4 64-bit

### ISSUE THREAD

**Issue by joao-pm-santos96** [zinen/docker-alpine-pigpiod#17]
Hi,
thank you for your work, in concept it should be all I need.

To put you on context, I'm using a 64-bit OS (Ubuntu Server 20) on my Raspberry Pi 4, 4Gb and need to control the GPIO remotely. Preferably, using a docker container would be ideal. I have tried a couple of things that I would like to share:

1) Directly using [this instructions](http://abyz.me.uk/rpi/pigpio/download.html) on the host OS made it possible to remotely control de GPIO. This tells us that is not a host OS related issue.

2) Adapting you Dockerfile to use ubuntu as it's base image 

```
# Based on Alpine, a tiny linux distribution
FROM ubuntu as builder
# Install basic package to compile source code
#RUN apk add alpine-sdk
RUN  apt-get update \
  && apt-get install -y wget unzip build-essential
# Follow the install guide from creator of pigpio, http://abyz.me.uk/rpi/pigpio/download.html
RUN wget --output-document=download.zip https://github.com/joan2937/pigpio/archive/master.zip \
# Downloaded content is placed inside specific folder to not be depended of branch naming from repo
    && mkdir download \
    && unzip -d download download.zip \
    && cd /download/* \
# Fix for compiling on Alpine, https://github.com/joan2937/pigpio/issues/107
    #&& sed -i -e 's/ldconfig/echo ldconfig disabled/g' Makefile \
    && make \
    && make install
# Start of new base image
FROM ubuntu
LABEL maintainer="zinen@users.noreply.github.com"
COPY --from=builder /usr/local /usr/local
# Copy app into image
COPY start.sh /start.sh
# Make sure file has execution permission
RUN chmod +x /start.sh
# Start app
CMD /start.sh
```

gave the following error (using or not the --privileged flag)

```
Checking who is listening/bound to port 8888 ...
/start.sh: 4: netstat: not found
...OK, no process is listing/bound to port 8888
Starting daemon pigpiod ...
pigpiod: error while loading shared libraries: libpigpio.so.1: cannot open shared object file: No such file or directory
... daemon stopped unexpectedly.
netstat -tlep | grep 8888
/start.sh: 24: netstat: not found
sleeping for 20 sec - we hope that this releases the bound TCP port 8888
end of sleep
netstat -tlep | grep 8888
/start.sh: 29: netstat: not found
... start.sh terminated
```

What should we try next?

**Comment by joao-pm-santos96** [comment]
First breakthrough! On [start.sh](./start.sh), changing ```pigpiod -g -a 1``` to ```pigpiod -g``` solves the issue and works, but still requires the --privileged flag. Working on fixing it

**Comment by zinen** [comment]
Awesome if you get this running on a 64-bit system. Do keep sharing! 

I can see why removing `-a 1` from the run command would solve some issues as i dont think DMA memory allocation is relevant in 64-bit systems.

But I don't understand why you would want your base image to be Ubuntu(it doesn't need to match the host OS). But then again i didn't start testing with Alpine when making this image. I tested with Debian at the time.

To solve the privileged thing you could find out where the host OS shares it peripherals. Running `ls /dev/*gpio*` on the host should revival something for you.

**Comment by joao-pm-santos96** [comment]
> But then again i didn't start testing with Alpine when making this image. I tested with Debian at the time.

Same here. Tried with Alpine and was also fixed. 

> To solve the privileged thing you could find out where the host OS shares it peripherals. Running `ls /dev/*gpio*` on the host should revival something for you.

Didn’t work. Tried the following:

- /dev/mem 
- /dev/gpiomem 
- /dev/gpiochip0
- /dev/gpiochip1
- /dev/ttyAMA0

with ```--cap-add=ALL``` but without success.

**Comment by zinen** [comment]
Tested some stuff on my rpi3 running Raspbian 64bit. I think i fixed the image by removing the `-a 1` from the 64-bit editions of the image.

Would you care to test this on your rpi4 and report back if it works?
`docker run --rm -it --privileged zinen2/alpine-pigpiod:dev-latest`

Also I haven't either found the right combination of privileges to give the container to access the gpios without `--privileged` flag.

**Comment by joao-pm-santos96** [comment]
I needed to add ```-p 8888:8888``` but after that it did work

> Also I haven't either found the right combination of privileges to give the container to access the gpios without `--privileged` flag.

My neither...

**Comment by joao-pm-santos96** [comment]
Maybe @joan2937 could give a help telling us which devices are needed...

**Comment by zinen** [comment]
This works for me. I'm still not done investigating but thought I would share my findings so far.

```powershell
docker run --rm -it -p 8888:8888 -v /dev:/dev --device-cgroup-rule 'a 1:* rwm' --cap-add CAP_SYS_RAWIO zinen2/alpine-pigpiod
```

Maybe less access could do it also but all that combined does the job. This is how i got there:

`-v /dev:/dev`:

Someone at [stack](https://stackoverflow.com/a/58953658/10599784) said that in order to run `mknod` (here in [pigpio](https://github.com/joan2937/pigpio/blob/cc17196c7586c3625ac8adf8f34838d320ffeda6/pigpio.c#L2739)) in order to make a loop device you need `/dev` mounted.

`--device-cgroup-rule 'a 1:* rwm'` 
[A blog](https://dev.to/jeetparekh/accessing-devices-from-inside-a-docker-container-without-using-the-privileged-flag-1dd8) mentioned that you can't just mount devices inside containers and expect your container to have read/write access. But adding a device-cgroup-rule should fix that.

`--cap-add CAP_SYS_RAWIO`
Again at [stack ](https://stackoverflow.com/questions/30059784/docker-access-to-raspberry-pi-gpio-pins)i found this capability mentioned.

**Comment by joao-pm-santos96** [comment]
Well, isn't giving rwm privileges to /dev the same as using the ```--privileged``` flag?

**Comment by zinen** [comment]
> Well, isn't giving rwm privileges to /dev the same as using the `--privileged` flag?

Privileged gives a bit more access to the host. But I think its close to it... so I'll say yes anyhow.

But it proves to me that I'm closing in on the access requirements of the pigpio library. I think I have improved it now.

As this also works fine for me on rpi3-64bit. Could you test it on your rpi4?
```powershell
docker run --rm -it -p 8888:8888 --device /dev/vcio --device /dev/mem --cap-add CAP_SYS_RAWIO zinen2/alpine-pigpiod
```

**Comment by kofm** [comment]
Tested as of today with Rpi4, not working

This is the output:
```Checking who is listening/bound to port 8888 ...
...OK, no process is listing/bound to port 8888
Starting daemon pigpiod ...
2071-07-13 22:58:24 initPagemapBlock: mmap dma block 0 failed (Invalid argument)
Can't initialise pigpio library
... daemon stopped unexpectedly.
netstat -tlep | grep 8888
sleeping for 20 sec - we hope that this releases the bound TCP port 8888```

**Comment by joao-pm-santos96** [comment]
Hello,
sorry for not giving any updates for a (big) while... 

This actually worked for me!

> ```powershell
> docker run --rm -it -p 8888:8888 --device /dev/vcio --device /dev/mem --cap-add CAP_SYS_RAWIO zinen2/alpine-pigpiod
> ```

Here is the output:

```
Checking who is listening/bound to port 8888 ...
...OK, no process is listing/bound to port 8888
Starting daemon pigpiod ...
```

**Comment by joao-pm-santos96** [comment]
Also, here is the docker-compose.yaml that I am using for this:

```
services:
  # PiGpiod
  pigpiod:
    container_name: pigpiod
    image: zinen2/alpine-pigpiod:latest
    ports:
      - "8888:8888"
    devices:
      - "/dev/vcio:/dev/vcio"
      - "/dev/mem:/dev/mem"
    cap_add: 
      - CAP_SYS_RAWIO
```

It seams to be working...
